[package]
name = "rust-gotham"
version = "0.1.0"
authors = ["Anton Muravev"]
edition = "2018"

[dependencies]
gotham = "0.3"
gotham_derive = "0.3"
hyper = "0.12"
serde = "1.0"
serde_json = "1.0"
futures = "0.1"
mime = "0.3"
mongodb = "0.3.11"
