[package]
name = "rust-hyper"
version = "0.1.0"
authors = ["Anton Muravev"]
edition = "2018"

[dependencies]
hyper = "0.12"
futures = "0.1"
log = "0.4"
pretty_env_logger = "0.3"
tokio = "0.1"
serde = "1.0"
serde_json = "1.0"
mongodb = "0.3.11"
